#!/usr/bin/env bash
##############################################################################
##
##  No nonsense start up script for UN*X
##
##############################################################################

cd wrapper
if [ -z "$2" ]; then
    sh gradlew "$1"
else
    sh gradlew "$1" -Parg="$2"
fi
cd ../
