project = "NÖN"
title = "NÖN Docs"
description = "Make cross-platform games in Lua and MoonScript"
format = "markdown"
style = true

file = {
  '../lib/lua/initializer.lua',
  '../lib/lua/accelerometer.lua',
  '../lib/lua/audio.lua',
  '../lib/lua/compass.lua',
  '../lib/lua/files.lua',
  '../lib/lua/graphics.lua',
  '../lib/lua/java.lua',
  '../lib/lua/keyboard.lua',
  '../lib/lua/mouse.lua',
  '../lib/lua/network.lua',
  '../lib/lua/system.lua',
  '../lib/lua/touch.lua'
}